title: Villainess Reversal: The Rose of Ruin
lang: en
description: >
  An otome-style visual novel where you play as a villainess noble, facing fate, rivalry, and the chance for redemption or ruin. Multiple endings, loops, and dramatic choices await.
author: Gota
created: 2025-04-24
